# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embeddingService.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embeddingService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65mbeddingService.proto\x12\x10\x65mbeddingService\"\x1a\n\x07Queries\x12\x0f\n\x07queries\x18\x01 \x03(\t\"\x86\x01\n\nEmbeddings\x12:\n\x10\x64\x65nse_embeddings\x18\x01 \x03(\x0b\x32 .embeddingService.DenseEmbedding\x12<\n\x11sparse_embeddings\x18\x02 \x03(\x0b\x32!.embeddingService.SparseEmbedding\"\x16\n\x05Query\x12\r\n\x05query\x18\x01 \x01(\t\" \n\x0e\x44\x65nseEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\"2\n\x0fSparseEmbedding\x12\x0f\n\x07indices\x18\x01 \x03(\r\x12\x0e\n\x06values\x18\x02 \x03(\x02\x32\xb2\x01\n\x10\x45mbeddingService\x12K\n\x10\x43reateEmbeddings\x12\x19.embeddingService.Queries\x1a\x1c.embeddingService.Embeddings\x12Q\n\x14\x43reateDenseEmbedding\x12\x17.embeddingService.Query\x1a .embeddingService.DenseEmbeddingB\x0fZ\rgo_grpc/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embeddingService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rgo_grpc/proto'
  _globals['_QUERIES']._serialized_start=44
  _globals['_QUERIES']._serialized_end=70
  _globals['_EMBEDDINGS']._serialized_start=73
  _globals['_EMBEDDINGS']._serialized_end=207
  _globals['_QUERY']._serialized_start=209
  _globals['_QUERY']._serialized_end=231
  _globals['_DENSEEMBEDDING']._serialized_start=233
  _globals['_DENSEEMBEDDING']._serialized_end=265
  _globals['_SPARSEEMBEDDING']._serialized_start=267
  _globals['_SPARSEEMBEDDING']._serialized_end=317
  _globals['_EMBEDDINGSERVICE']._serialized_start=320
  _globals['_EMBEDDINGSERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
