// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: embedding.proto

package GoMemory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Queries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []string               `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queries) Reset() {
	*x = Queries{}
	mi := &file_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queries) ProtoMessage() {}

func (x *Queries) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queries.ProtoReflect.Descriptor instead.
func (*Queries) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *Queries) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

type Embeddings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DenseEmbeddings  []*DenseEmbedding      `protobuf:"bytes,1,rep,name=dense_embeddings,json=denseEmbeddings,proto3" json:"dense_embeddings,omitempty"`
	SparseEmbeddings []*SparseEmbedding     `protobuf:"bytes,2,rep,name=sparse_embeddings,json=sparseEmbeddings,proto3" json:"sparse_embeddings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Embeddings) Reset() {
	*x = Embeddings{}
	mi := &file_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embeddings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embeddings) ProtoMessage() {}

func (x *Embeddings) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embeddings.ProtoReflect.Descriptor instead.
func (*Embeddings) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *Embeddings) GetDenseEmbeddings() []*DenseEmbedding {
	if x != nil {
		return x.DenseEmbeddings
	}
	return nil
}

func (x *Embeddings) GetSparseEmbeddings() []*SparseEmbedding {
	if x != nil {
		return x.SparseEmbeddings
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_embedding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{2}
}

func (x *Query) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type DenseEmbedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenseEmbedding) Reset() {
	*x = DenseEmbedding{}
	mi := &file_embedding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenseEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenseEmbedding) ProtoMessage() {}

func (x *DenseEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenseEmbedding.ProtoReflect.Descriptor instead.
func (*DenseEmbedding) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{3}
}

func (x *DenseEmbedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type SparseEmbedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []uint32               `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SparseEmbedding) Reset() {
	*x = SparseEmbedding{}
	mi := &file_embedding_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SparseEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparseEmbedding) ProtoMessage() {}

func (x *SparseEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparseEmbedding.ProtoReflect.Descriptor instead.
func (*SparseEmbedding) Descriptor() ([]byte, []int) {
	return file_embedding_proto_rawDescGZIP(), []int{4}
}

func (x *SparseEmbedding) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *SparseEmbedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_embedding_proto protoreflect.FileDescriptor

const file_embedding_proto_rawDesc = "" +
	"\n" +
	"\x0fembedding.proto\x12\x10embeddingService\"#\n" +
	"\aQueries\x12\x18\n" +
	"\aqueries\x18\x01 \x03(\tR\aqueries\"\xa9\x01\n" +
	"\n" +
	"Embeddings\x12K\n" +
	"\x10dense_embeddings\x18\x01 \x03(\v2 .embeddingService.DenseEmbeddingR\x0fdenseEmbeddings\x12N\n" +
	"\x11sparse_embeddings\x18\x02 \x03(\v2!.embeddingService.SparseEmbeddingR\x10sparseEmbeddings\"\x1d\n" +
	"\x05Query\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"(\n" +
	"\x0eDenseEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"C\n" +
	"\x0fSparseEmbedding\x12\x18\n" +
	"\aindices\x18\x01 \x03(\rR\aindices\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values2\xb2\x01\n" +
	"\x10EmbeddingService\x12K\n" +
	"\x10CreateEmbeddings\x12\x19.embeddingService.Queries\x1a\x1c.embeddingService.Embeddings\x12Q\n" +
	"\x14CreateDenseEmbedding\x12\x17.embeddingService.Query\x1a .embeddingService.DenseEmbeddingB&Z$github.com/Prateek-Gupta001/GoMemoryb\x06proto3"

var (
	file_embedding_proto_rawDescOnce sync.Once
	file_embedding_proto_rawDescData []byte
)

func file_embedding_proto_rawDescGZIP() []byte {
	file_embedding_proto_rawDescOnce.Do(func() {
		file_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embedding_proto_rawDesc), len(file_embedding_proto_rawDesc)))
	})
	return file_embedding_proto_rawDescData
}

var file_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_embedding_proto_goTypes = []any{
	(*Queries)(nil),         // 0: embeddingService.Queries
	(*Embeddings)(nil),      // 1: embeddingService.Embeddings
	(*Query)(nil),           // 2: embeddingService.Query
	(*DenseEmbedding)(nil),  // 3: embeddingService.DenseEmbedding
	(*SparseEmbedding)(nil), // 4: embeddingService.SparseEmbedding
}
var file_embedding_proto_depIdxs = []int32{
	3, // 0: embeddingService.Embeddings.dense_embeddings:type_name -> embeddingService.DenseEmbedding
	4, // 1: embeddingService.Embeddings.sparse_embeddings:type_name -> embeddingService.SparseEmbedding
	0, // 2: embeddingService.EmbeddingService.CreateEmbeddings:input_type -> embeddingService.Queries
	2, // 3: embeddingService.EmbeddingService.CreateDenseEmbedding:input_type -> embeddingService.Query
	1, // 4: embeddingService.EmbeddingService.CreateEmbeddings:output_type -> embeddingService.Embeddings
	3, // 5: embeddingService.EmbeddingService.CreateDenseEmbedding:output_type -> embeddingService.DenseEmbedding
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_embedding_proto_init() }
func file_embedding_proto_init() {
	if File_embedding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embedding_proto_rawDesc), len(file_embedding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embedding_proto_goTypes,
		DependencyIndexes: file_embedding_proto_depIdxs,
		MessageInfos:      file_embedding_proto_msgTypes,
	}.Build()
	File_embedding_proto = out.File
	file_embedding_proto_goTypes = nil
	file_embedding_proto_depIdxs = nil
}
